//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brobet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bet()
        {
            this.Transactions = new HashSet<Transaction>();
            this.FromBetObjects = new HashSet<BetObject>();
            this.ToBetObjects = new HashSet<BetObject>();
        }
    
        public int id { get; set; }
        public int fromUserId { get; set; }
        public int toUserId { get; set; }
        public int fixtureId { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public Nullable<int> winnerId { get; set; }
        public int fromAmount { get; set; }
        public int toAmount { get; set; }
    
        public virtual Fixture Fixture { get; set; }
        public virtual User FromUser { get; set; }
        public virtual User ToUser { get; set; }
        public virtual User Winner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetObject> FromBetObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetObject> ToBetObjects { get; set; }
    }
}
