//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brobet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public int userId { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public Nullable<int> betId { get; set; }
        public Nullable<int> betRequestId { get; set; }
    
        public virtual Bet Bet { get; set; }
        public virtual User User { get; set; }
        public virtual BetRequest BetRequest { get; set; }
    }
}
